kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30092
        hostPort: 9092
      - containerPort: 30074
        hostPort: 7474
      - containerPort: 30687
        hostPort: 7687
