apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JonatasRodriguesReis/portfolio-mlops-inference-platform-infra.git
    targetRevision: main
    path: k8s/apps/inference

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
