apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-apps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: inference=ghcr.io/jonatasrodriguesreis/portfolio-mlops-inference-platform-app
    argocd-image-updater.argoproj.io/inference.update-strategy: newest-build
    argocd-image-updater.argoproj.io/inference.allow-tags: regexp:^20.*
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/JonatasRodriguesReis/portfolio-mlops-inference-platform-infra.git
    targetRevision: main
    path: k8s/apps/inference

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
