apiVersion: batch/v1
kind: Job
metadata:
  name: locust-load-test
  namespace: mlops-inference-app
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: locust
          image: locustio/locust:2.24.0
          env:
            - name: LOCUST_USERS
              value: "100"
            - name: LOCUST_RATE
              value: "5"
            - name: LOCUST_DURATION
              value: "1m"
          command:
            - sh
            - -c
            - |
              locust -f /mnt/locustfile.py \
                --headless \
                -u ${LOCUST_USERS} \
                -r ${LOCUST_RATE} \
                --run-time ${LOCUST_DURATION} \
                --host http://inference-api.mlops-inference-app.svc.cluster.local
          volumeMounts:
            - name: locustfile
              mountPath: /mnt
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
